# -*- coding: utf-8 -*-
"""pandas_intro_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl7lhKe1HV8kltVWPT01XVucVBKdO4mN

# Atividade 1 — Exercícios com os comandos básicos de pandas para EDA


Responda as perguntas abaixo no notebook (cada resposta deve ter ao menos uma célula de código que produza o output e, logo abaixo, uma célula de texto com a sua interpretação).

## 1) Carregue o dataset e mostre as primeiras 10 linhas.
"""

import pandas as pd
df = pd.read_csv('/content/emendas.csv')
df.head(10)

"""```
# Isto está formatado como código
```

Código da Emenda,Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso	Código Município IBGE	Município	Código UF IBGE	...	Código Ação	Nome Ação	Código Plano Orçamentário	Nome Plano Orçamentário	Valor Empenhado	Valor Liquidado	Valor Pago	Valor Restos A Pagar Inscritos	Valor Restos A Pagar Cancelados	Valor Restos A Pagar Pagos.

## 2) Quantas linhas e colunas o dataset possui?
"""

df.shape

"""n_linhas e n_colunas

## 3) Liste os nomes das colunas e descreva brevemente o que você entende que cada coluna representa.
"""

df.dtypes

"""cada coluna representa uma função: Código da Emenda, Ano da Emenda,Tipo de Emenda,Código do Autor da Emenda,Nome do Autor da Emenda,Número da emenda,Localidade de aplicação do recurso,Código Município IBGE,Município,Código UF IBGE,UF, Região,Código Função,Nome Função,Código Subfunção Nome Subfunção	object
Código Programa
Nome Programa
Código Ação
Nome Ação
Código Plano Orçamentário
Nome Plano Orçamentário
Valor Empenhado
Valor Liquidado
Valor Pago
Valor Restos A Pagar Inscritos
Valor Restos A Pagar Cancelados
Valor Restos A Pagar Pagos

## 4) Existem valores nulos? quantos?
"""

nulos = df.isnull().sum()
print(nulos)

"""## 5) Mostre os tipos das variáveis (se int, string, boolean, float...) e analise se alguma variável parece ter o tipo errado. Faça isso da maneira mais objetiva e otimizada possível."""

df.info()

"""Se alguma coluna estiver com o tipo errado, escreva abaixo qual é e por que isso pode atrapalhar análises.

**Dica:** Se alguma variável tiver no tipo o nome "object", isso se refere a texto.

## 6) Usando a coluna `Ano da Emenda` como base, descubra até que ano o dataset está atualizado (mostre as 8 primeiras linhas do df ordenado desc).
"""

df_ordenado = df.sort_values(by='Ano da Emenda', ascending=False)
print(df_ordenado.head(8))

"""Explique: qual é o ano mais recente presente no dataset?
Resposta: 2025

## 7) execute um  `describe()` e explique uma conclusão simples que você consegue tirar a partir das estatísticas (se algumas colunas deveriam aparecer no describe mas não aparecem, indique o motivo que você acredita que esteja causando esse problema).
"""

df.describe()

"""## 8) Mostre as últimas 5 linhas do dataset e escreva se a última linha parece completa (sem muitos nulos) ou não."""

df.tail(5)

"""Interprete a completude da última linha.

## 9) existem valores duplicados no dataframe? Caso positivo, quantos?
"""

total_duplicates = df.duplicated().sum()
print(total_duplicates)